image: docker:latest

stages:
  - build

variables:
    IMAGE:   "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}"

docker-build:
  stage: build
  script:
    - docker build --tag "${IMAGE}" .
    - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN}" "${CI_REGISTRY}"
    - docker push "${IMAGE}"
